
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include "utils.h"
#include "string.h"
#include "sylk.h"


#define print_help() \
{ \
    printf("usage: %s <file_name> [-a] [-b] [-h]\n", argv[0]); \
    printf("help:\n"); \
    printf("\t<file_name> : file with code to execute\n"); \
    printf("\t-a          : dump the abstract syntax tree\n"); \
    printf("\t-b          : dump the generated bytecodes\n"); \
    printf("\t-h          : not execute the program\n"); \
}

struct my_ctx {
    const char* text;
};

static struct sylk_object test_fun(struct sylk_object* self, struct sylk_vm* vm, void* ctx) {
    (void) self;
    (void) vm;

    struct my_ctx* mctx = ctx;

    printf("%s\n", mctx->text);
    return (struct sylk_object){};
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        print_help();
        return 1;
    }

    bool print_ast = false;
    bool print_bytecode = false;
    bool halt_program = false;

    // parse flags
    int index = 2;
    while (index < argc) {
        const char* current_arg = argv[index];
        if (strlen(current_arg) != 2) {
            print_help();
            return 1;
        }

        if (current_arg[0] != '-') {
            print_help();
            return 1;
        }

        switch (current_arg[1]) {
            case 'a':
                print_ast = true;
                break;

            case 'b':
                print_bytecode = true;
                break;

            case 'h':
                halt_program = true;
                break;
            default:
                print_help();
                return 1;
        }

        ++index;
    }

    struct sylk_config config = {
        .print_ast = print_ast,
        .print_bytecode = print_bytecode,
        .halt_program = halt_program
    };

    struct my_ctx ctx = {
        .text = "hello world"
    };

    struct sylk* s = sylk_new(&config, &ctx);

    sylk_load_prelude(s);

    struct sylk_function functions[] = {
        {"test", test_fun, 0},
        {NULL, NULL, 0}
    };

    sylk_load_functions(s, functions);

    const char* members[] = {
        NULL
    };

    struct sylk_class classes[] = {
        {"Test", members, functions},
        {NULL, NULL, NULL}
    };

    sylk_load_classes(s, classes);

    CHECK(sylk_run_file(s, argv[1]), "failed to run file");
    sylk_free(s);
}
